# Generated by Django 5.1.4 on 2025-01-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
